#/***************************************************************************
# ${TemplateClass}
#
# ${TemplateDescription}
#							 -------------------
#		begin				: $TemplateBuildDate
#		copyright			: (C) $TemplateYear by $TemplateAuthor
#		email				: $TemplateEmail
# ***************************************************************************/
#
#/***************************************************************************
# *																		 *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU General Public License as published by  *
# *   the Free Software Foundation; either version 2 of the License, or	 *
# *   (at your option) any later version.								   *
# *																		 *
# ***************************************************************************/

#################################################
# Edit the following to match your sources lists
#################################################

# translation
SOURCES = \
	__init__.py \
	${TemplateModuleName}.py \
	${TemplateModuleName}_dialog.py

#TRANSLATIONS = i18n/${TemplateModuleName}_en.ts
TRANSLATIONS =

PLUGINNAME = ${TemplateClass}

PY_FILES = \
	${TemplateModuleName}.py \
	${TemplateModuleName}_dialog.py \
	__init__.py

EXTRAS = icon.png metadata.txt

COMPILED_UI_FILES = ${TemplateModuleName}_dialog_base.py

COMPILED_RESOURCE_FILES = resources_rc.py


#################################################
# Normally you would not need to edit below here
#################################################

HELP = help/build/html

PLUGIN_UPLOAD = $$(CURDIR)/plugin_upload.py

QGISDIR=.qgis2

default: compile

compile: $$(COMPILED_UI_FILES) $$(COMPILED_RESOURCE_FILES)

%_rc.py : %.qrc
	pyrcc4 -o $$*_rc.py  $$<

%.py : %.ui
	pyuic4 -o $$@ $$<

%.qm : %.ts
	lrelease $$<


deploy: compile doc transcompile
	@echo
	@echo "------------------------------------------"
	@echo "Deploying plugin to your .qgis2 directory."
	@echo "------------------------------------------"
	# The deploy  target only works on unix like operating system where
	# the Python plugin directory is located at:
	# $$HOME/$$(QGISDIR)/python/plugins
	mkdir -p $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)
	cp -vf $$(PY_FILES) $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)
	cp -vf $$(COMPILED_UI_FILES) $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)
	cp -vf $$(COMPILED_RESOURCE_FILES) $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)
	cp -vf $$(EXTRAS) $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)
	cp -vfr i18n $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)
	cp -vfr $$(HELP) $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)/help

# The dclean target removes compiled python files from plugin directory
# also delets any .svn entry
dclean:
	@echo
	@echo "-----------------------------------"
	@echo "Removing any compiled python files."
	@echo "-----------------------------------"
	find $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME) -iname "*.pyc" -delete
	find $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME) -iname ".svn" -prune -exec rm -Rf {} \;


derase:
	@echo
	@echo "-------------------------"
	@echo "Removing deployed plugin."
	@echo "-------------------------"
	rm -Rf $$(HOME)/$$(QGISDIR)/python/plugins/$$(PLUGINNAME)

zip: deploy dclean
	@echo
	@echo "---------------------------"
	@echo "Creating plugin zip bundle."
	@echo "---------------------------"
	# The zip target deploys the plugin and creates a zip file with the deployed
	# content. You can then upload the zip file on http://plugins.qgis.org
	rm -f $$(PLUGINNAME).zip
	cd $$(HOME)/$$(QGISDIR)/python/plugins; zip -9r $$(CURDIR)/$$(PLUGINNAME).zip $$(PLUGINNAME)

package: compile
	# Create a zip package of the plugin named $$(PLUGINNAME).zip.
	# This requires use of git (your plugin development directory must be a
	# git repository).
	# To use, pass a valid commit or tag as follows:
	#   make package VERSION=Version_0.3.2
	@echo
	@echo "------------------------------------"
	@echo "Exporting plugin to zip package.	"
	@echo "------------------------------------"
	rm -f $$(PLUGINNAME).zip
	git archive --prefix=$$(PLUGINNAME)/ -o $$(PLUGINNAME).zip $$(VERSION)
	echo "Created package: $$(PLUGINNAME).zip"

upload: zip
	@echo
	@echo "-------------------------------------"
	@echo "Uploading plugin to QGIS Plugin repo."
	@echo "-------------------------------------"
	$$(PLUGIN_UPLOAD) $$(PLUGINNAME).zip

transup:
	@echo
	@echo "------------------------------------------------"
	@echo "Updating translation files with any new strings."
	@echo "------------------------------------------------"
	pylupdate4 Makefile

transcompile:
	@echo
	@echo "----------------------------------------"
	@echo "Compiled translation files to .qm files."
	@echo "----------------------------------------"
	$$(TRANSLATIONS:.ts=.qm)

transclean:
	@echo
	@echo "------------------------------------"
	@echo "Removing compiled translation files."
	@echo "------------------------------------"
	rm -f i18n/*.qm

clean:
	@echo
	@echo "------------------------------------"
	@echo "Removing uic and rcc generated files"
	@echo "------------------------------------"
	rm $$(COMPILED_UI_FILES) $$(COMPILED_RESOURCE_FILES)

doc:
	@echo
	@echo "------------------------------------"
	@echo "Building documentation using sphinx."
	@echo "------------------------------------"
	cd help; make html

pylint:
	@echo
	@echo "-----------------"
	@echo "Pylint violations"
	@echo "-----------------"
	@pylint --reports=n --rcfile=pylintrc safe . || true


# Run pep8 style checking
#http://pypi.python.org/pypi/pep8
pep8:
	@echo
	@echo "-----------"
	@echo "PEP8 issues"
	@echo "-----------"
	@pep8 --repeat --ignore=E203,E121,E122,E123,E124,E125,E126,E127,E128 --exclude pydev,${TemplateModuleName}_dialog_base.py,resources_rc.py . || true
